# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-19 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20170917_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Customer'),
        ),
    ]
