# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-01 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20170918_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Current_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
