# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-03 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_stock_current_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='Current_price',
        ),
    ]
